### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 3)

### ISSUE THREAD

**Issue by MartinThoma** [xuhdev/flake8-executable#15]
When I have it installed, I get:

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/math/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/math/.pyenv/versions/3.8.6/lib/python3.8/site-packages/flake8/checker.py", line 676, in _run_checks
    return checker.run_checks()
  File "/home/math/.pyenv/versions/3.8.6/lib/python3.8/site-packages/flake8/checker.py", line 589, in run_checks
    self.run_ast_checks()
  File "/home/math/.pyenv/versions/3.8.6/lib/python3.8/site-packages/flake8/checker.py", line 494, in run_ast_checks
    for (line_number, offset, text, _) in runner:
ValueError: not enough values to unpack (expected 4, got 3)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/math/.pyenv/versions/3.8.6/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/math/.pyenv/versions/3.8.6/lib/python3.8/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/math/.pyenv/versions/3.8.6/lib/python3.8/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/home/math/.pyenv/versions/3.8.6/lib/python3.8/site-packages/flake8/main/application.py", line 351, in _run
    self.run_checks()
  File "/home/math/.pyenv/versions/3.8.6/lib/python3.8/site-packages/flake8/main/application.py", line 264, in run_checks
    self.file_checker_manager.run()
  File "/home/math/.pyenv/versions/3.8.6/lib/python3.8/site-packages/flake8/checker.py", line 321, in run
    self.run_parallel()
  File "/home/math/.pyenv/versions/3.8.6/lib/python3.8/site-packages/flake8/checker.py", line 287, in run_parallel
    for ret in pool_map:
  File "/home/math/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
ValueError: not enough values to unpack (expected 4, got 3)
```

with Flake8 3.8.4

**Comment by xuhdev** [comment]
Sorry for the late reply -- for some reason I didn't see this issue. This should have been fixed in the latest version 2.1.1. Thank you for the report!
